Repository woowa-techcamp-2021/deal-15, pull requests merged in 2021-07, with the labels that each got.

#11 프로젝트 기본 골격 만들기
  .devcontainer/devcontainer.json
  .vscode/settings.json
  README.md
  client/.devcontainer/Dockerfile
  client/.devcontainer/devcontainer.json
  client/.eslintrc.json
  client/.gitignore
  client/.prettierrc
  client/.vscode/settings.json
  client/README.md
  client/package-lock.json
  client/package.json
  server/.devcontainer/Dockerfile
  server/.devcontainer/devcontainer.json
  server/.eslintrc.json
  server/.gitignore
  server/.prettierrc
  server/.vscode/settings.json
  server/README.md
  server/package-lock.json
  server/package.json
Labels: enhancement

#16 [feature/#14] 백엔드 베이스 코드 작성
  server/package-lock.json
  server/package.json
  server/sample.env
  server/src/app.js
  server/src/bin/www
  server/src/config/index.js
Labels: backend, enhancement

#17 [feature/#13] 클라이언트 베이스 코드 작성했습니다.
  client/.browserslistrc
  client/.devcontainer/devcontainer.json
  client/.eslintrc.json
  client/.prettierignore
  client/babel.config.json
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/src/index.html
  client/src/index.js
  client/src/styles/global.scss
  client/src/styles/reset.css
  client/webpack.common.js
  client/webpack.dev.js
  client/webpack.prod.js
Labels: enhancement, frontend

#22 [feature/#21] eslint 설정 삭제
  client/.devcontainer/devcontainer.json
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  server/.devcontainer/devcontainer.json
  server/.eslintrc.json
  server/package-lock.json
  server/package.json
Labels: enhancement

#23 [feature/#20] 컴포넌트 베이스 코드 작성
  .vscode/settings.json
  client/src/components/Component.js
  client/src/components/TestComponent.js
  client/src/index.js
  client/src/pages/TestPage.js
Labels: enhancement, frontend

#25 [feature/#24] 폰트, 컬러 css 변수 추가
  client/src/styles/theme.scss
Labels: enhancement, frontend

#27 [hotfix/css-variable] color-grey1 중복 수정
  client/src/styles/theme.scss
Labels: bug, frontend

#28 [feature/#26] icon font 파일 추가
  client/src/assets/fonts/woowa-market-icons.css
  client/src/assets/fonts/woowa-market-icons.woff
  client/src/assets/fonts/woowa-market-icons.woff2
  client/src/index.js
  client/webpack.common.js
Labels: enhancement, frontend

#54 [feature/#51] 컴포넌트 베이스 코드 변경
  client/src/components/component.js
  client/src/components/test-component.js
Labels: enhancement, frontend

#58 global.scss에 box-sizing 항목 추가
  client/src/styles/global.scss
Labels: enhancement, frontend

#55 [feature/#29] 버튼 공통 컴포넌트 작성
  client/src/components/button/button-category.js
  client/src/components/button/button-fab.js
  client/src/components/button/button-location.js
  client/src/components/button/button-normal.js
  client/src/components/button/button-status.js
  client/src/components/button/button-tab.js
  client/src/index.js
  client/src/pages/TestPage.js
  client/src/pages/button-test-page.js
  client/src/styles/components/button/button-category.module.scss
  client/src/styles/components/button/button-fab.module.scss
  client/src/styles/components/button/button-location.module.scss
  client/src/styles/components/button/button-normal.module.scss
  client/src/styles/components/button/button-status.module.scss
  client/src/styles/components/button/button-tab.module.scss
  client/src/styles/global.scss
Labels: enhancement, frontend

#61 [feature/#60] css module 디버그용 설정 및 asset/resource 설정 변경
  client/webpack.common.js
  client/webpack.dev.js
  client/webpack.prod.js
Labels: enhancement, frontend

#57 [feature/#30] text-input 공통 컴포넌트 작성
  client/src/components/text-input/text-input.js
  client/src/pages/text-input-test-page.js
  client/src/styles/components/text-input/text-input.module.scss
Labels: enhancement, frontend

#62 [feature/#31] ImgBox 컴포넌트 작성
  client/src/components/img-box/img-box.js
  client/src/pages/img-box-test-page.js
  client/src/styles/components/img-box/img-box.module.scss
Labels: enhancement, frontend

#64 [feature/#59] server api routing 기본 골격 작성
  server/src/app.js
  server/src/core/error/api-error.js
  server/src/route/api/v1/auth.js
  server/src/route/api/v1/categories.js
  server/src/route/api/v1/chats.js
  server/src/route/api/v1/images.js
  server/src/route/api/v1/index.js
  server/src/route/api/v1/products.js
  server/src/route/api/v1/users.js
Labels: backend, enhancement

#63 [feature/#33] ChatBubble 컴포넌트 작성
  client/src/components/chat-bubble/chat-bubble.js
  client/src/pages/chat-bubble-test-page.js
  client/src/styles/components/chat-bubble/chat-bubble.module.scss
Labels: enhancement, frontend

#71 [feature/#70] server 코드에 module-alias를 사용해서 webpack의 resolve.alias와 같이 사용할 수 있음
  server/.devcontainer/devcontainer.json
  server/package-lock.json
  server/package.json
  server/src/bin/www
Labels: backend, enhancement

#65 [feature/#34] ChatBadge 컴포넌트 작성
  client/src/components/chat-badge/chat-badge.js
  client/src/pages/chat-badge-test-page.js
  client/src/styles/components/chat-badge/chat-badge.module.scss
Labels: enhancement, frontend

#66 [feature/#35] CategoryListItem 컴포넌트 작성
  client/src/components/category-list-item/category-list-item.js
  client/src/components/img-box/img-box.js
  client/src/pages/category-list-item-test-page.js
  client/src/styles/components/category-list-item/category-list-item.module.scss
Labels: enhancement, frontend

#75 [feature/#74] server 코드에 nodemon을 설치하여 자동으로 서버가 재실행 되게 만들었습니다.
  server/package-lock.json
  server/package.json
Labels: backend, enhancement

#76 [feature/#72] jwt 인증 처리 및 server 상세 구조 작성
  server/.devcontainer/devcontainer.json
  server/jsconfig.json
  server/package-lock.json
  server/package.json
  server/sample.env
  server/src/app.js
  server/src/bin/www
  server/src/config/index.js
  server/src/config/jwt.js
  server/src/core/error/api-error.js
  server/src/dao/refresh-token.js
  server/src/dao/user.js
  server/src/model/refresh-token.js
  server/src/model/user.js
  server/src/route/api/v1/auth.js
  server/src/route/api/v1/index.js
  server/src/service/jwt.js
Labels: backend, enhancement

#82 [feature/#78] client 코드에 jsconfig.json을 추가했습니다.
  client/jsconfig.json
Labels: enhancement, frontend

#84 [feature/#81] Component -> component
  client/src/components/button/button-category.js
  client/src/components/button/button-fab.js
  client/src/components/button/button-location.js
  client/src/components/button/button-normal.js
  client/src/components/button/button-status.js
  client/src/components/button/button-tab.js
  client/src/components/category-list-item/category-list-item.js
  client/src/components/chat-badge/chat-badge.js
  client/src/components/chat-bubble/chat-bubble.js
  client/src/components/img-box/img-box.js
  client/src/components/test-component.js
  client/src/components/text-input/text-input.js
  client/src/pages/button-test-page.js
  client/src/pages/category-list-item-test-page.js
  client/src/pages/chat-badge-test-page.js
  client/src/pages/chat-bubble-test-page.js
  client/src/pages/img-box-test-page.js
  client/src/pages/text-input-test-page.js
Labels: bug, frontend

#67 [feature/#36] ImgButton 컴포넌트 작성.
  client/src/assets/images/button-default.svg
  client/src/components/img-box/img-box.js
  client/src/components/img-button/img-button.js
  client/src/pages/img-button-test-page.js
  client/src/styles/components/img-box/img-box.module.scss
  client/src/styles/components/img-button/img-button.module.scss
  client/src/styles/global.scss
Labels: enhancement, frontend

#68 [feature/#37] DropDown 컴포넌트 작성.
  client/src/components/drop-down/drop-down.js
  client/src/components/img-box/img-box.js
  client/src/pages/drop-down-test-page.js
  client/src/pages/img-button-test-page.js
  client/src/styles/components/drop-down/drop-down.module.scss
Labels: enhancement, frontend

#79 [feature/#39] TabBar 컴포넌트 작성.
  client/src/components/button/button-tab.js
  client/src/components/tab-bar/tab-bar.js
  client/src/pages/tab-bar-test-page.js
  client/src/styles/components/button/button-tab.module.scss
  client/src/styles/components/tab-bar/tab-bar.module.scss
  client/src/styles/theme.scss
Labels: enhancement, frontend

#80 [feature/#40] ImgNav 컴포넌트 작성
  client/src/components/img-nav/img-nav.js
  client/src/pages/img-nav-test-page.js
  client/src/styles/components/img-nav/img-nav.module.scss
Labels: enhancement, frontend

#83 [feature/#41] InfoSaler 컴포넌트 작성
  client/src/components/info-saler/info-saler.js
  client/src/pages/info-saler-test-page.js
  client/src/styles/components/info-saler/info-saler.module.scss
Labels: enhancement, frontend

#85 [feature/#42] ProductBar 컴포넌트 작성
  client/src/components/product-bar/product-bar.js
  client/src/pages/product-bar-test-page.js
  client/src/styles/components/product-bar/product-bar.module.scss
Labels: enhancement, frontend

#86 [feaure/#43] location-bar 컴포넌트 작성
  client/src/components/location-bar/location-bar.js
  client/src/pages/location-bar-test-page.js
  client/src/styles/components/location-bar/location-bar.module.scss
Labels: enhancement, frontend

#87 [feature/#45] chat-bar 컴포넌트 작성
  client/src/components/chat-bar/chat-bar.js
  client/src/pages/chat-bar-test-page.js
  client/src/styles/components/chat-bar/chat-bar.module.scss
Labels: enhancement, frontend

#88 [feature/#46] alert 컴포넌트 작성
  client/src/components/alert/alert.js
  client/src/pages/alert-test-page.js
  client/src/styles/components/alert/alert.module.scss
  client/src/styles/global.scss
Labels: enhancement, frontend

#89 [feature/#47] info-product 컴포넌트 작성
  client/src/components/info-product/info-product.js
  client/src/pages/info-product-test-page.js
  client/src/styles/components/info-product/info-product.module.scss
Labels: enhancement, frontend

#98 [feature/#91] 채팅 기능을 제외한 서버 API 작업을 마쳤습니다.
  server/.gitignore
  server/nodemon.json
  server/package-lock.json
  server/package.json
  server/sample.env
  server/src/app.js
  server/src/config/mysql.js
  server/src/core/db-connection.js
  server/src/dao/category.js
  server/src/dao/db.js
  server/src/dao/file.js
  server/src/dao/product.js
  server/src/dao/refresh-token.js
  server/src/dao/user.js
  server/src/dto/product-detail.js
  server/src/dto/product-refresh.js
  server/src/dto/product-simple.js
  server/src/middleware/invalid-request.js
  server/src/middleware/wrap-async.js
  server/src/model/category.js
  server/src/model/image.js
  server/src/model/product-image.js
  server/src/model/product.js
  server/src/model/refresh-token.js
  server/src/model/user.js
  server/src/model/watch.js
  server/src/route/api/v1/auth.js
  server/src/route/api/v1/categories.js
  server/src/route/api/v1/images.js
  server/src/route/api/v1/products.js
  server/src/route/api/v1/users.js
  server/src/service/category.js
  server/src/service/file.js
  server/src/service/jwt.js
  server/src/service/product.js
  server/src/service/user.js
Labels: backend, enhancement

#99 [feature/#97] 상품 상세 페이지 작성.
  client/src/components/img-box/img-box.js
  client/src/components/img-nav/img-nav.js
  client/src/components/product-bar/product-bar.js
  client/src/index.js
  client/src/pages/main-page/main-page.js
  client/src/pages/main-page/sub-page/menu-page.js
  client/src/pages/product-page/product-detail-page.js
  client/src/pages/product-page/sub-page/chat-page.js
  client/src/styles/components/img-box/img-box.module.scss
  client/src/styles/components/img-nav/img-nav.module.scss
  client/src/styles/components/product-bar/product-bar.module.scss
  client/src/styles/pages/product-page/product-detail-page.module.scss
  client/src/styles/pages/product-page/sub-page/chat-page.module.scss
  client/src/utils/api.js
Labels: enhancement, frontend

#102 [hotfox/#101] 254를 256으로 변경
  server/sample.env
Labels: backend, bug

#106 [fefactoring/#105] 지금까지 완성된 화면 style 리팩토링
  client/.prettierrc
  client/src/assets/images/not-found.png
  client/src/components/drop-down/drop-down.js
  client/src/components/product-list-item/product-list-item.js
  client/src/index.js
  client/src/pages/404-page.js
  client/src/pages/main-page/main-page.js
  client/src/pages/main-page/sub-page/account-page.js
  client/src/pages/main-page/sub-page/category-page.js
  client/src/pages/main-page/sub-page/menu-page.js
  client/src/pages/product-page/product-detail-page.js
  client/src/pages/product-page/sub-page/chat-page.js
  client/src/styles/common.module.scss
  client/src/styles/components/chat-list-item/chat-list-item.module.scss
  client/src/styles/components/header/header-main.module.scss
  client/src/styles/components/product-list-item/product-list-item.module.scss
  client/src/styles/global.scss
  client/src/styles/pages/404-page.module.scss
  client/src/styles/pages/main-page/main-page.module.scss
  client/src/styles/pages/main-page/sub-page/account-page.module.scss
  client/src/styles/pages/main-page/sub-page/category-page.module.scss
  client/src/styles/pages/main-page/sub-page/menu-page.module.scss
  client/src/styles/pages/product-page/product-detail-page.module.scss
  client/src/styles/pages/product-page/sub-page/chat-page.module.scss
  client/webpack.common.js
Labels: enhancement, frontend, refactoring

#110 [hotfix/category-request-body] 이미지 파일 이름 길이 제한 제거
  server/src/route/api/v1/categories.js
Labels: backend, bug

#112 [feature/#111] 사진 업로드 api 추가
  client/src/components/header/header-menu.js
  client/src/utils/api.js
Labels: enhancement, frontend

#113 [feature/#100] 메인화면과 로그인화면 쪽 api 연결했습니다.
  client/src/assets/images/chat.jpg
  client/src/assets/images/empty.png
  client/src/components/header/header-menu.js
  client/src/index.js
  client/src/pages/main-page/main-page.js
  client/src/pages/main-page/sub-page/account-page.js
  client/src/pages/main-page/sub-page/category-page.js
  client/src/pages/main-page/sub-page/menu-page.js
  client/src/styles/components/header/header-menu.module.scss
  client/src/styles/pages/main-page/sub-page/menu-page.module.scss
  client/src/utils/api.js
Labels: enhancement, frontend

#117 [hotfix/api] ProductSimple type 오류 수정
  server/src/dto/product-simple.js
  server/src/model/product.js
Labels: backend, bug

#118 [hotfix/api] createdDatetime 오타 수정
  server/src/dto/product-detail.js
Labels: backend, bug

#120 [hotfix/me_like] 자기 추천 금지 해제
  server/src/service/product.js
Labels: backend

#121 [feature/#114] 메인화면과 상세 화면 api를 가다듬었습니다.
  client/src/components/drop-down/drop-down.js
  client/src/components/product-list-item/product-list-item.js
  client/src/pages/main-page/main-page.js
  client/src/pages/main-page/sub-page/menu-page.js
  client/src/pages/main-page/sub-page/set-location-page.js
  client/src/pages/product-page/product-detail-page.js
  client/src/styles/components/alert/alert.module.scss
  client/src/styles/components/img-box/img-box.module.scss
  client/src/styles/components/input-popup/input-popup.module.scss
  client/src/styles/components/product-list-item/product-list-item.module.scss
  client/src/utils/api.js
Labels: enhancement, frontend
